name: CI

on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: branch-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OK
        run: echo "Branch is ready to merge"
