name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff bandit
          # Se precisar de outras dependências para o bandit/ruff rodarem:
          # pip install -r requirements.txt

      - name: Auto-fix & Lint
        run: |
          # O ruff e bandit agora são chamados diretamente
          ruff format .
          ruff check . --fix --unsafe-fixes 
          bandit -r app/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix and linting"
